CLOUD-2968 Move base layer of AMQ image from jboss-openjdk to rhel7
jboss-container-images/jboss-amq-6-image pull request #60
Opened 2018-11-29 10:51 UTC by gaohoward

Update the amq63 base image to latest.
Also use content_set as perfered by cekit 2.2.x.

Signed-off-by: Howard Gao <howard.gao@gmail.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2018-11-29 10:54 UTC, goldmann requested changes
Look good, but you're missing the container section in osbs section so that OSBS can use defined repositories.

2018-11-29 11:02 UTC, gaohoward commented
@goldmann ok will change it. Thanks!

2018-11-29 16:14 UTC, gaohoward commented
@goldmann Hi Marek, just pushed the changes, Pls review. Thanks!
Howard

2018-11-29 16:24 UTC, goldmann commented on image.yaml
> +    - path: jboss-a-mq-6.3.0.redhat-356.zip
Optional: use `name` instead of `path`. This way the artifact is fetched directly from Brew and there is no need from cacher. More on the blog.

2018-11-29 16:24 UTC, goldmann commented
Looks good now, just added one comment, see above. This is optional for now, so approving.

2018-11-29 16:25 UTC, goldmann submitted a review, later dismissed

2018-11-30 02:56 UTC, gaohoward commented
@goldmann Thanks. I've updated the image.yaml (using name instead of path) could you approve it again?

2018-11-30 08:07 UTC, goldmann submitted a review, later dismissed
Great, it looks perfect now!

2019-11-01 04:30 UTC, gaohoward commented
close as it is outdated.

2019-11-01 04:30 UTC, closed without merging